In [2]:
#NumPy is centered around 'arrays' which are more efficient & convenient than Python lists
import numpy as np

In [4]:
#A one-dimensional array is compared to Python lists as it stores a list of numbers 
#Data in an array are called 'elements' and are accessed using brackets []
#A two-dimensional array has a grid structure with rows and columns
#A three-dimensional arrray is a stack of two-dimensional arrays

a = np.array([1, 2, 3, 4, 5])                      #Dimensions = 'axes'
print(a[0])                                        #No. of axes = 'rank'  -> a is an array of rank 1
print(a[4])

1
5


In [14]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])         #b has a rank of 2  --> Note the use of brackets
print(b)
print(b[1, 3])                                  #Prints the 2nd list of numbers and the index 3 in that list
print(b.ndim)                                   #Prints the rank number
print(b.shape)                                  #Prints [NO. OF ROWS, NO. OF COLUMNS]
print(b.size)                                   #Prints no. of elements
print(type(b))                                  #Prints element type

[[1 2 3 4]
 [5 6 7 8]]
8
2
(2, 4)
8
<class 'numpy.ndarray'>


In [189]:
c = np.ones((3, 2))                            #Creates an array of ones presented in 3 ranks with 2 dimensions
print(c)
print('\n')
d = np.zeros((4, 4))
print(d)
print('\n')
e = np.random.random(5)                        #Creates an array of (x) random values
print(e)
print('\n')
f = np.full((2, 5), 10)                        #Creates an array of tens presented in 2 ranks with 5 dimensions
print(f)
print('\n')
g = np.empty([2, 10])                          #Similar to 'np.random.random' 
print(g)
print('\n')
h = np.full((2, 5), 2, dtype=np.float32)       #Can specify which format -> float format or integer format (int)
print(h)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[0.71765543 0.42987726 0.71679846 0.40043122 0.33354933]


[[10 10 10 10 10]
 [10 10 10 10 10]]


[[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.37961166e-306
  2.22523004e-307 1.24611606e-306 1.69119194e-306 8.90104917e-307
  4.45058486e-308 1.78019761e-306]
 [9.34608432e-307 8.01097889e-307 1.78020169e-306 7.56601165e-307
  1.02359984e-306 2.31420176e-306 8.01089062e-307 9.34603679e-307
  8.45590539e-307 1.37961641e-306]]


[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


In [71]:
#Creating a sequence
x = np.arange(0, 20, 4)             #Creates a numpy array with values between 0-20 incremented by 4 - Returns up to 20
print(x)

y = np.arange(10)
print(y)

z = np.linspace(0, 20, 5)           #Creates 5 values between 0-20 evenly spaced - Returns specified number of elements
print(z)

[ 0  4  8 12 16]
[0 1 2 3 4 5 6 7 8 9]
[ 0.  5. 10. 15. 20.]


In [190]:
#Changing array shape and size
print(y.shape)
y.resize(2, 5)                                        #Only 'resize' changes the contents of given array
print(y.shape)
print(y)

print('\n')

b2 = np.array([[1, 2, 3], [5, 6, 7]])  
print(b2.shape)
print(b2)
print('\n')
print(b2.reshape(3, 2))
print(b2.shape)
print('\n')
print(b2.ravel())                                     #Creates a non-seperated ('flattened') array

(2, 5)
(2, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]]


(2, 3)
[[1 2 3]
 [5 6 7]]


[[1 2]
 [3 5]
 [6 7]]
(2, 3)


[1 2 3 5 6 7]


In [84]:
j = np.array([[2, 4, 6, 8,], [10, 12, 14, 16]])
print(j.transpose())                                

[[ 2 10]
 [ 4 12]
 [ 6 14]
 [ 8 16]]


In [110]:
#Array slicing
k = np.arange(6)
print(k)
print(k.shape)
print(k[0:4])
print(k[0:4:2])
print(k[:5:2])
k2 = k[4:]                                                  #Item 4 onwards (non-inclusive)
print(k2)

k2[1] = 99                                                 #Changing values in a sub-array of original array
print(k2)
print(k)

print('\n')


l = np.array([[10, 20, 30, 40, 50], [60, 70, 80, 90, 100]])
print(l[0:2, 1])                                              #1 refers to index position in both
print(l[0:2, 2])                                              #2 refers to index position in both
print(l[0:1, 2])                                              #2nd digit refers to in what row (1 = 1st row only)
print(l[..., 4])                                              #Ellipsis ('...,') refers to 4th index in each row
print(l[ : , 4])                                              #Does the same as '...,'

[0 1 2 3 4 5]
(6,)
[0 1 2 3]
[0 2]
[0 2 4]
[4 5]
[ 4 99]
[ 0  1  2  3  4 99]


[20 70]
[30 80]
[30]
[ 50 100]
[ 50 100]


In [191]:
#Arithmetic functions
l = np.array([[10, 20, 30, 40, 50], [60, 70, 80, 90, 100]])
j = np.array([[2, 4, 6, 8, 10], [10, 12, 14, 16, 18]])
print(np.add(l, j))
print('\n')
print(np.divide(l, j))
print('\n')
print(np.subtract(l, j))
print('\n')
print(np.multiply(l, j))
                                                                   #'np.dot' can be used for matrix multiplication 
print('\n')

print(l**2)
print('\n')
print(l - j)
print('\n')
print(l > 50)                                                      #Boolean Logic can also be implemented with arrays

[[ 12  24  36  48  60]
 [ 70  82  94 106 118]]


[[5.         5.         5.         5.         5.        ]
 [6.         5.83333333 5.71428571 5.625      5.55555556]]


[[ 8 16 24 32 40]
 [50 58 66 74 82]]


[[  20   80  180  320  500]
 [ 600  840 1120 1440 1800]]


[[  100   400   900  1600  2500]
 [ 3600  4900  6400  8100 10000]]


[[ 8 16 24 32 40]
 [50 58 66 74 82]]


[[False False False False False]
 [ True  True  True  True  True]]


In [192]:
#Elementwise functions
b2 = np.array([[1, 2, 3], [5, 6, 7]])  
print(np.exp(b2))                                                    #'np.exp' calculates the exponential of each item
print('\n')
t = np.sqrt(b2)                                                      #'np.sqrt' calculates the square root of each item
print(t)
print('\n')
print(np.around(t, 3))                              #'np.around()' rounds elements to a specified no. of decimal places
print('\n')
print(np.trunc(t))                                  #'np.trunc' shortens (truncates) elements in an array
print('\n')
print(np.log(t))                                    #'np.log' calculates natural  log for all elements 

[[   2.71828183    7.3890561    20.08553692]
 [ 148.4131591   403.42879349 1096.63315843]]


[[1.         1.41421356 1.73205081]
 [2.23606798 2.44948974 2.64575131]]


[[1.    1.414 1.732]
 [2.236 2.449 2.646]]


[[1. 1. 1.]
 [2. 2. 2.]]


[[0.         0.34657359 0.54930614]
 [0.80471896 0.89587973 0.97295507]]


In [149]:
b23= np.array([[1.5, 2.6, 3.4], [5.1, 6, 7]])
print(np.floor(b23))                                #'np.floor' calculates greatest integer >= to a value (Rounds down)
print(np.ceil(b23))                                 #'np.ceil' calculates smallest integer >=  to a value (Rounds up)

[[1. 2. 3.]
 [5. 6. 7.]]
[[2. 3. 4.]
 [6. 6. 7.]]


In [186]:
#Array Functions
n = np.array([[10, 20, 30, 40, 50], [60, 70, 80, 90, 100]])
m = np.array([[2, 4, 6, 8, 10], [10, 12, 14, 16, 18]])
print(n.sum(axis = 0))
print(m.sum(axis = 0))
print('\n')
print(np.max(n))
print(np.min(n))
print(np.max(m))
print(np.min(n))
print('\n')
print(n.max(axis = 1))                                      #'axis = 1' represents the row (Max in each row)
print(n.min(axis = 1))
print(m.max(axis = 1))
print(m.min(axis = 1))
print('\n')
print(np.cumsum(n))
print(np.cumsum(m))
print('\n')
print(np.corrcoef(n))                                       #Calculates correlation co-efficient of elements in 'n'
print(np.corrcoef(m))
print('\n')
print(n.std())                                              #Calculates standard deviation of elements in 'n'
print(m.std())
print('\n')
print(np.mean(n))
print(np.mean(m))
print('\n')
print(np.median(n))
print(np.median(m))

[ 70  90 110 130 150]
[12 16 20 24 28]


100
10
18
10


[ 50 100]
[10 60]
[10 18]
[ 2 10]


[ 10  30  60 100 150 210 280 360 450 550]
[  2   6  12  20  30  40  52  66  82 100]


[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]


28.722813232690143
4.898979485566356


55.0
10.0


55.0
10.0


In [185]:
#Broadcasting                                     Requires that arrays have the same dimensions OR corresponding dimension be 1
twod = np.array([[1, 4, 6, 8,], [1, 12, 14, 16]])
oned = np.array([[10]])
threed = np.ones((2, 4))          #'np.ones' creates an array of ones in dimension (2, 4)
test = np.ones((3,2))

print(np.add(twod, oned))
print('\n')
print(np.add(oned, threed))
print('\n')
print(np.add(twod, threed))     #No error -> Dimensions of 'twod' match dimensions of 'threed'
print('\n')
print(np.add(twod, test))         #Expected error -> Dimensions are not the same -> Broadcasting can't make them the same

[[11 14 16 18]
 [11 22 24 26]]


[[11. 11. 11. 11.]
 [11. 11. 11. 11.]]


[[ 2.  5.  7.  9.]
 [ 2. 13. 15. 17.]]




ValueError: operands could not be broadcast together with shapes (2,4) (3,2) 