In [9]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [16]:
#Merge column
df1 = DataFrame({'key':['a', 'b', 'c', 'a', 'b', 'b'],'data_set_1':np.arange(6)})
df1

key  data_set_1
0   a           0
1   b           1
2   c           2
3   a           3
4   b           4
5   b           5

In [20]:
df2 = DataFrame({'key':['a', 'y', 'c'],'data_set_2': ['1', '2', '3']})
df2

key data_set_2
0   a          1
1   y          2
2   c          3

In [21]:
pd.merge(df1, df2)                                                     #Overlapped where keys matched

key  data_set_1 data_set_2
0   a           0          1
1   a           3          1
2   c           2          3

In [22]:
pd.merge(df1, df2, on = 'key')                                         #Same result as automatic merging

key  data_set_1 data_set_2
0   a           0          1
1   a           3          1
2   c           2          3

In [26]:
ex = pd.merge(df1, df2, on = 'key', how = 'left')                          #C values are null as C doesn't overlap
ex
#ex.fillna(10)

key  data_set_1 data_set_2
0   a           0          1
1   b           1        NaN
2   c           2          3
3   a           3          1
4   b           4        NaN
5   b           5        NaN

In [24]:
df2

key data_set_2
0   a          1
1   y          2
2   c          3

In [27]:
ex2 = pd.merge(df1, df2, on = 'key', how = 'right')          #'right' indicates right row ie. 'data_set_2'
ex2

key  data_set_1 data_set_2
0   a         0.0          1
1   a         3.0          1
2   c         2.0          3
3   y         NaN          2

In [28]:
pd.merge(df1, df2, on = 'key', how = 'outer')                                    #Uses both left & right 

key  data_set_1 data_set_2
0   a         0.0          1
1   a         3.0          1
2   b         1.0        NaN
3   b         4.0        NaN
4   b         5.0        NaN
5   c         2.0          3
6   y         NaN          2

In [29]:
df3 = DataFrame({'key': ['X', 'Y', 'Z', 'X', 'X', 'Z'], 'data_set_3': range(6)})
df3

key  data_set_3
0   X           0
1   Y           1
2   Z           2
3   X           3
4   X           4
5   Z           5

In [30]:
df4 = DataFrame({'key': ['Y', 'Y', 'Z', 'Z', 'X'], 'data_set_4': range(5)})
df4

key  data_set_4
0   Y           0
1   Y           1
2   Z           2
3   Z           3
4   X           4

In [31]:
pd.merge(df3, df4)

key  data_set_3  data_set_4
0   X           0           4
1   X           3           4
2   X           4           4
3   Y           1           0
4   Y           1           1
5   Z           2           2
6   Z           2           3
7   Z           5           2
8   Z           5           3

In [32]:
pd.merge(df3, df4, on = 'key', how = 'left')

key  data_set_3  data_set_4
0   X           0           4
1   Y           1           0
2   Y           1           1
3   Z           2           2
4   Z           2           3
5   X           3           4
6   X           4           4
7   Z           5           2
8   Z           5           3

In [41]:
dfex = DataFrame({'key1': ['PHX', 'LA', 'NYC'], 
                  'key2': ['1', '2', '3'], 
                  'data1': [10, 20, 30]}
                )
dfex

key1 key2  data1
0  PHX    1     10
1   LA    2     20
2  NYC    3     30

In [42]:
dfex2 = DataFrame({'key1': ['PHX', 'PHX', 'LA', 'LA'],
                            'key2': ['1', '2', '1', '2'], 
                            'data2':[50, 60, 70, 80]}
                            )
dfex2

key1 key2  data2
0  PHX    1     50
1  PHX    2     60
2   LA    1     70
3   LA    2     80

In [44]:
graph = pd.merge(dfex, dfex2, on = ['key1', 'key2'], how = 'outer')
graph

key1 key2  data1  data2
0  PHX    1   10.0   50.0
1   LA    2   20.0   80.0
2  NYC    3   30.0    NaN
3  PHX    2    NaN   60.0
4   LA    1    NaN   70.0

In [45]:
graph.fillna('X')

key1 key2 data1 data2
0  PHX    1    10    50
1   LA    2    20    80
2  NYC    3    30     X
3  PHX    2     X    60
4   LA    1     X    70

In [46]:
pd.merge(dfex, dfex2, on = 'key1')
#Pandas automaticallly keeps columns seperated (with suffix) when one key is called but 2 exist

key1 key2_x  data1 key2_y  data2
0  PHX      1     10      1     50
1  PHX      1     10      2     60
2   LA      2     20      1     70
3   LA      2     20      2     80

In [48]:
pd.merge(dfex, dfex2, on = 'key1', suffixes = ('_#1', '_#2'))      #Can create your own suffix

key1 key2_#1  data1 key2_#2  data2
0  PHX       1     10       1     50
1  PHX       1     10       2     60
2   LA       2     20       1     70
3   LA       2     20       2     80

In [50]:
#LINK TO MERGE IN PANDAS DOCUMENTATION
import webbrowser                                                    
websites = 'http://pandas-docs.github.io/pandas-docs-travis/merging.html'
webbrowser.open(websites)

True

In [51]:
#Merge index
df100 = DataFrame({'key': ['X', 'Y', 'Z', 'X', 'Y'], 'data100':range(5)})
df100

key  data100
0   X        0
1   Y        1
2   Z        2
3   X        3
4   Y        4

In [52]:
df200 = DataFrame({'test': [10, 20]}, index = ['X', 'Y'])
df200

test
X    10
Y    20

In [53]:
pd.merge(df100, df200, left_on = 'key', right_index = True)

key  data100  test
0   X        0    10
3   X        3    10
1   Y        1    20
4   Y        4    20

In [135]:
df500 = DataFrame({'key2': ['DUB', 'DUB', 'BER', 'BER', 'DUB'], 'key3': [10, 20, 20, 30, 40], 'data1000': np.arange(5.0)})
df500

key2  key3  data1000
0  DUB    10       0.0
1  DUB    20       1.0
2  BER    20       2.0
3  BER    30       3.0
4  DUB    40       4.0

In [136]:
#Index hierarchy = list of lists [[]]
df600 = DataFrame(np.arange(10).reshape(5, 2), 
                  index = [['BER', 'BER', 'DUB', 'DUB', 'BER'], 
                           [40, 30, 20, 10, 5]],
                 columns =  ['Col1', 'Col2'])
df600

Col1  Col2
BER 40     0     1
    30     2     3
DUB 20     4     5
    10     6     7
BER 5      8     9

In [137]:
pd.merge(df500, df600, left_on = ['key2', 'key3'], right_index = True)     #Adds 'df600' to right of'df500'

key2  key3  data1000  Col1  Col2
0  DUB    10       0.0     6     7
1  DUB    20       1.0     4     5
3  BER    30       3.0     2     3

In [141]:
#df500.join(df600)                                   '.join()' can also be used 

In [67]:
#Concatenate
array = np.arange(10).reshape(5,2)
array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [68]:
np.concatenate([array, array], axis = 1 )

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5],
       [6, 7, 6, 7],
       [8, 9, 8, 9]])

In [69]:
np.concatenate([array, array], axis = 0)                #Top - Bottom format

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9],
       [0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [74]:
ser1 = Series([0, 1, 2], index = ['A','B', 'C'])
ser2 = Series([1, 10], index = ['X', 'Y'])

In [75]:
ser1

A    0
B    1
C    2
dtype: int64

In [76]:
ser2

X     1
Y    10
dtype: int64

In [77]:
pd.concat([ser1, ser2])

A     0
B     1
C     2
X     1
Y    10
dtype: int64

In [79]:
pd.concat([ser1, ser2], axis = 1, sort = False)                #Creates a DataFrame

0     1
A  0.0   NaN
B  1.0   NaN
C  2.0   NaN
X  NaN   1.0
Y  NaN  10.0

In [80]:
pd.concat([ser1, ser2], keys = ['One', 'Two'])            #Labelling of 2 different series'

One  A     0
     B     1
     C     2
Two  X     1
     Y    10
dtype: int64

In [86]:
dframe = DataFrame(np.random.randn(4, 3), columns = ['A', 'B', 'C'])

dframe2 = DataFrame(np.random.randn(3, 3), columns = ['X', 'B', 'C'])

In [87]:
dframe

A         B         C
0  0.610373  0.014489  1.203886
1 -0.339590 -0.254448 -0.705292
2 -1.148212 -0.504538 -0.090541
3 -0.555641 -0.693392  0.004105

In [88]:
dframe2

X         B         C
0  0.861907 -0.046979 -0.154063
1 -0.115550 -0.014928  0.711068
2 -0.869359 -0.739820 -0.090725

In [95]:
con = pd.concat([dframe, dframe2], sort = False)
con

A         B         C         X
0  0.610373  0.014489  1.203886       NaN
1 -0.339590 -0.254448 -0.705292       NaN
2 -1.148212 -0.504538 -0.090541       NaN
3 -0.555641 -0.693392  0.004105       NaN
0       NaN -0.046979 -0.154063  0.861907
1       NaN -0.014928  0.711068 -0.115550
2       NaN -0.739820 -0.090725 -0.869359

In [97]:
con.fillna('NULL')

A         B         C         X
0  0.610373  0.014489  1.203886      NULL
1  -0.33959 -0.254448 -0.705292      NULL
2  -1.14821 -0.504538 -0.090541      NULL
3 -0.555641 -0.693392  0.004105      NULL
0      NULL -0.046979 -0.154063  0.861907
1      NULL -0.014928  0.711068  -0.11555
2      NULL -0.739820 -0.090725 -0.869359

In [94]:
pd.concat([dframe, dframe2], ignore_index = True, sort = False)    #'ignore_index' calls a continuous index

A         B         C         X
0  0.610373  0.014489  1.203886       NaN
1 -0.339590 -0.254448 -0.705292       NaN
2 -1.148212 -0.504538 -0.090541       NaN
3 -0.555641 -0.693392  0.004105       NaN
4       NaN -0.046979 -0.154063  0.861907
5       NaN -0.014928  0.711068 -0.115550
6       NaN -0.739820 -0.090725 -0.869359

In [98]:
#Combining DataFrames
ser100 = Series([10, np.nan, 20, np.nan, 30, np.nan], index = ['A', 'B', 'C', 'D', 'E', 'F'])
ser100

A    10.0
B     NaN
C    20.0
D     NaN
E    30.0
F     NaN
dtype: float64

In [102]:
ser200 = Series(len(ser100), dtype = np.float64, 
                   index = ['A', 'B', 'C', 'D', 'E', 'F'])
ser200

A    6.0
B    6.0
C    6.0
D    6.0
E    6.0
F    6.0
dtype: float64

In [108]:
Series(np.where(pd.isnull(ser100), ser200, ser100), index = ser100.index)   #Method #1
#Indicating to fill in 'ser100' null values with 'ser200' values

A    10.0
B     6.0
C    20.0
D     6.0
E    30.0
F     6.0
dtype: float64

In [109]:
ser100.combine_first(ser200)                                                #Method #2

A    10.0
B     6.0
C    20.0
D     6.0
E    30.0
F     6.0
dtype: float64

In [112]:
nan = np.nan
dfr = DataFrame({'x': [1., nan, 3., nan, 5., nan],
                'y': [7., nan, 9., nan, 11., nan],
                'z': [13., nan, 15., nan, 17., nan]})
dfr

x     y     z
0  1.0   7.0  13.0
1  NaN   NaN   NaN
2  3.0   9.0  15.0
3  NaN   NaN   NaN
4  5.0  11.0  17.0
5  NaN   NaN   NaN

In [115]:
dfr2 = DataFrame({'x': [2., 4., nan, 6., 8.],
                'y': [nan, 10., 12., 14., 16.]})
dfr2

x     y
0  2.0   NaN
1  4.0  10.0
2  NaN  12.0
3  6.0  14.0
4  8.0  16.0

In [118]:
dfr.combine_first(dfr2)

x     y     z
0  1.0   7.0  13.0
1  4.0  10.0   NaN
2  3.0   9.0  15.0
3  6.0  14.0   NaN
4  5.0  11.0  17.0
5  NaN   NaN   NaN

In [120]:
#Reshaping
dataframe = DataFrame(np.arange(8).reshape(2, 4), 
                      index = pd.Index(['NYC', 'BER'], name = 'City'),
                       columns = pd.Index(['A', 'B', 'C', 'D'], name = 'Letter ->'))          #pd.index'' allows naming 
dataframe

Letter ->  A  B  C  D
City                 
NYC        0  1  2  3
BER        4  5  6  7

In [121]:
dfr120 = dataframe.stack()                       #Reverts it to a Series
dfr120

City  Letter ->
NYC   A            0
      B            1
      C            2
      D            3
BER   A            4
      B            5
      C            6
      D            7
dtype: int32

In [122]:
dfr120.unstack()                           #Reverts back to  a DataFrame

Letter ->  A  B  C  D
City                 
NYC        0  1  2  3
BER        4  5  6  7

In [124]:
dfr120.unstack('City')

City       NYC  BER
Letter ->          
A            0    4
B            1    5
C            2    6
D            3    7

In [125]:
series9 = Series([0, 1, 2], index = ['X', 'Y', 'Z'])
series99 = Series([3, 4, 5], index = ['Q', 'X', 'Y'])

In [126]:
conc =  pd.concat([series9, series99], keys = ['First', 'Second'])
conc

First   X    0
        Y    1
        Z    2
Second  Q    3
        X    4
        Y    5
dtype: int64

In [127]:
conc.unstack()

Q    X    Y    Z
First   NaN  0.0  1.0  2.0
Second  3.0  4.0  5.0  NaN

In [128]:
conc.unstack().stack()                              #Restacking removes null values

First   X    0.0
        Y    1.0
        Z    2.0
Second  Q    3.0
        X    4.0
        Y    5.0
dtype: float64

In [129]:
conc2 = conc.unstack()                              #Stores as a variable
conc2

Q    X    Y    Z
First   NaN  0.0  1.0  2.0
Second  3.0  4.0  5.0  NaN

In [131]:
conc2.stack(dropna = False)                        #Doesn't remove null values

First   Q    NaN
        X    0.0
        Y    1.0
        Z    2.0
Second  Q    3.0
        X    4.0
        Y    5.0
        Z    NaN
dtype: float64