In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
#Pivot Tables
import webbrowser
website = 'https://en.wikipedia.org/wiki/Pivot_table'
webbrowser.open(website)

True

In [3]:
#import pandas testing utility
import pandas.util.testing as tm; tm.N = 3

#Create a unpivoted function
def unpivot(frame):
    N, K = frame.shape
    
    data = {'value' : frame.values.ravel('F'),
            'variable' : np.asarray(frame.columns).repeat(N),
            'date' : np.tile(np.asarray(frame.index), K)}
    
    #Return the DataFrame
    return DataFrame(data, columns=['date', 'variable', 'value'])

#Set the DataFrame we'll be using
dframe = unpivot(tm.makeTimeDataFrame())

In [4]:
dframe

date variable     value
0  2000-01-03        A  0.793245
1  2000-01-04        A  0.228927
2  2000-01-05        A -1.005476
3  2000-01-03        B -0.507345
4  2000-01-04        B -1.019777
5  2000-01-05        B  0.133351
6  2000-01-03        C -1.033311
7  2000-01-04        C -2.413539
8  2000-01-05        C -0.073885
9  2000-01-03        D -2.158396
10 2000-01-04        D -1.017795
11 2000-01-05        D -0.811000

In [5]:
dframepiv = dframe.pivot('date', 'variable', 'value')              #Must be exact same spelling as in DataFrame
dframepiv

variable           A         B         C         D
date                                              
2000-01-03  0.793245 -0.507345 -1.033311 -2.158396
2000-01-04  0.228927 -1.019777 -2.413539 -1.017795
2000-01-05 -1.005476  0.133351 -0.073885 -0.811000

In [6]:
#Duplicates in DataFrames
dfr = DataFrame({'Key1': ['A']*2 + ['B']*3 + ['C']*2,
                'Key2': [2, 2, 2, 3, 3, 10, 10]})
dfr

Key1  Key2
0    A     2
1    A     2
2    B     2
3    B     3
4    B     3
5    C    10
6    C    10

In [7]:
dfr.duplicated()                                            #To see if any rows are duplicated (second instance)

0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [8]:
dfr.drop_duplicates()                                       #Removes duplicates (Only prints 'False' values from above)

Key1  Key2
0    A     2
2    B     2
3    B     3
5    C    10

In [9]:
dfr.drop_duplicates(['Key2'])                              #Removes duplicates from 2nd column ONLY

Key1  Key2
0    A     2
3    B     3
5    C    10

In [10]:
dfr.drop_duplicates(['Key1'])                              #Removes duplicates from 1st column ONLY

Key1  Key2
0    A     2
2    B     2
5    C    10

In [11]:
dfr.drop_duplicates(['Key1'], keep = 'last')              #Only keeps last occurrences  of a key  

Key1  Key2
1    A     2
4    B     3
6    C    10

In [15]:
#Mapping
df100 = DataFrame({'City':['Berlin', 'London', 'Barcelona'],
                  'Altitude':['3000', '6000', '9000']})
df100

City Altitude
0     Berlin     3000
1     London     6000
2  Barcelona     9000

In [16]:
df200 = {'Berlin': 'Germany', 'London': 'UK', 'Barcelona': 'Spain'}
df200

{'Berlin': 'Germany', 'London': 'UK', 'Barcelona': 'Spain'}

In [17]:
df100['Country'] = df100['City'].map(df200)                               #'.map()' method is the easiest way to 'map' new values

In [18]:
df100

City Altitude  Country
0     Berlin     3000  Germany
1     London     6000       UK
2  Barcelona     9000    Spain

In [19]:
df100.head(1)

City Altitude  Country
0  Berlin     3000  Germany

In [21]:
#Replace
series = Series([1, 2, 3, 4, 1, 2, 3, 4])
series

0    1
1    2
2    3
3    4
4    1
5    2
6    3
7    4
dtype: int64

In [22]:
series.replace(2, 5)

0    1
1    5
2    3
3    4
4    1
5    5
6    3
7    4
dtype: int64

In [23]:
series.replace(4, np.nan)

0    1.0
1    2.0
2    3.0
3    NaN
4    1.0
5    2.0
6    3.0
7    NaN
dtype: float64

In [24]:
series.replace([2, 4], [200, 400])                               #Replacing multiple elements of a series

0      1
1    200
2      3
3    400
4      1
5    200
6      3
7    400
dtype: int64

In [26]:
series.replace({3:300})                                          #Can be replaced by passing dictionaries

0      1
1      2
2    300
3      4
4      1
5      2
6    300
7      4
dtype: int64

In [28]:
#Rename Index
df500 = DataFrame(np.arange(10).reshape(2, 5),
                 index = ['BER', 'TOR'],
                 columns = ['A', 'B', 'C', 'D', 'E'])
df500

A  B  C  D  E
BER  0  1  2  3  4
TOR  5  6  7  8  9

In [29]:
df500.index.map(str.lower)

Index(['ber', 'tor'], dtype='object')

In [32]:
df500.index = df500.index.map(str.lower)

In [33]:
df500

A  B  C  D  E
ber  0  1  2  3  4
tor  5  6  7  8  9

In [35]:
df500.rename(index = str.title, columns = str.lower)

a  b  c  d  e
Ber  0  1  2  3  4
Tor  5  6  7  8  9

In [38]:
df500.rename(index = {'ber': 'BERLIN'},
            columns = {'A': 'ALPHA'})

ALPHA  B  C  D  E
BERLIN      0  1  2  3  4
tor         5  6  7  8  9

In [39]:
df500

A  B  C  D  E
ber  0  1  2  3  4
tor  5  6  7  8  9

In [40]:
df500.rename(index = {'ber': 'BERLIN'}, inplace = True)                     #Effects are permanent due to 'inplace = True'

In [41]:
df500

A  B  C  D  E
BERLIN  0  1  2  3  4
tor     5  6  7  8  9

In [48]:
#Binning
years = [1990, 1992, 1996, 2002, 2010, 2020, 2005, 2000, 2012]

In [49]:
decades = [1960, 1970, 1980, 1990, 2000, 2010, 2020]

In [50]:
decade_cat = pd.cut(years, decades)
decade_cat

[(1980, 1990], (1990, 2000], (1990, 2000], (2000, 2010], (2000, 2010], (2010, 2020], (2000, 2010], (1990, 2000], (2010, 2020]]
Categories (6, interval[int64]): [(1960, 1970] < (1970, 1980] < (1980, 1990] < (1990, 2000] < (2000, 2010] < (2010, 2020]]

In [51]:
decade_cat.categories

IntervalIndex([(1960, 1970], (1970, 1980], (1980, 1990], (1990, 2000], (2000, 2010], (2010, 2020]]
              closed='right',
              dtype='interval[int64]')

In [52]:
pd.value_counts(decade_cat)

(2000, 2010]    3
(1990, 2000]    3
(2010, 2020]    2
(1980, 1990]    1
(1970, 1980]    0
(1960, 1970]    0
dtype: int64

In [53]:
pd.cut(years, 2, precision = 1)                                        #'(x, y]' indicates open at x and close at y inclusive

[(1990.0, 2005.0], (1990.0, 2005.0], (1990.0, 2005.0], (1990.0, 2005.0], (2005.0, 2020.0], (2005.0, 2020.0], (1990.0, 2005.0], (1990.0, 2005.0], (2005.0, 2020.0]]
Categories (2, interval[float64]): [(1990.0, 2005.0] < (2005.0, 2020.0]]

In [54]:
#Outliers
np.random.seed(12345)

In [57]:
df1000 = DataFrame(np.random.randn(1000, 4))
df1000.head()

0         1         2         3
0 -1.166530 -0.075264  0.112345  0.166874
1  0.012628  0.815313 -0.732001  0.868791
2  0.149693  0.485218  0.161056 -1.068808
3  1.190359 -1.053204  0.776001  1.311260
4  1.159677  0.477395 -0.004493  0.574631

In [58]:
df1000.tail()

0         1         2         3
995 -1.530608  0.058991 -0.337120  1.129394
996 -0.151214 -0.898121 -1.467595 -1.086964
997 -0.104017  1.442214 -1.713617  0.936543
998  1.932427  0.530258 -0.217213  0.988951
999  0.193746 -1.744483  0.761804 -1.544201

In [60]:
df1000.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.039859    -0.033350    -0.011749    -0.031858
std       1.004647     0.998154     0.987471     1.013590
min      -3.530912    -3.024110    -3.170292    -3.105636
25%      -0.738643    -0.698731    -0.692887    -0.758010
50%       0.011608    -0.016171     0.022570    -0.035527
75%       0.663800     0.605952     0.666451     0.693491
max       2.916153     3.061029     2.623689     3.144389

In [98]:
test1 = df1000[1]
test1

0     -0.075264
1      0.815313
2      0.485218
3     -1.053204
4      0.477395
5      0.179143
6     -1.605282
7      0.387475
8     -1.130313
9     -0.374624
10    -2.578745
11    -1.311494
12    -0.257655
13    -0.957547
14    -0.667538
15    -1.252866
16     1.468470
17    -0.674705
18     0.676456
19     0.525463
20    -0.847705
21    -0.957573
22     0.310997
23     1.521939
24    -0.419068
25     0.980018
26    -2.132729
27     0.433803
28    -1.893589
29     0.450543
         ...   
970   -0.100395
971   -0.622362
972   -1.254419
973   -0.701517
974   -1.856139
975   -0.636650
976   -1.122094
977   -0.838081
978   -1.836319
979   -0.294997
980   -0.210137
981   -0.534875
982    0.400544
983   -0.224531
984   -2.036302
985    0.937367
986    0.993970
987    0.741331
988    0.568452
989   -0.428339
990   -2.066349
991   -0.495209
992    2.853399
993   -0.426999
994   -0.625729
995    0.058991
996   -0.898121
997    1.442214
998    0.530258
999   -1.744483
Name: 1, Length: 1000, d

In [99]:
test1[np.abs(test1) > 3]

Series([], Name: 1, dtype: float64)

In [100]:
test2 = df1000[2]
test2

0      0.112345
1     -0.732001
2      0.161056
3      0.776001
4     -0.004493
5      1.115972
6     -0.833580
7     -0.297376
8      0.385064
9      1.229986
10     0.952680
11    -0.801136
12    -1.262446
13    -2.051322
14     0.293062
15    -0.817687
16     0.204320
17     1.038180
18    -2.939965
19     0.543670
20    -0.893508
21    -0.496932
22    -2.651410
23     1.355408
24     0.791332
25     1.046478
26     0.922325
27    -0.385785
28    -2.170980
29    -0.425955
         ...   
970   -0.190284
971    1.356795
972   -0.741076
973    0.564843
974    0.414117
975   -2.082545
976   -0.395760
977    1.879510
978   -0.430815
979   -0.083922
980   -1.187029
981   -0.348527
982   -0.697276
983    0.229793
984   -0.744430
985   -1.197221
986   -1.842897
987   -0.208422
988    0.118484
989   -0.294842
990   -0.845268
991   -0.421000
992   -1.194400
993    0.045162
994    0.586007
995   -0.337120
996   -1.467595
997   -1.713617
998   -0.217213
999    0.761804
Name: 2, Length: 1000, d

In [94]:
test2[np.abs(test2) > 3]

Series([], Name: 2, dtype: float64)

In [95]:
test3 = df1000[3]

In [96]:
test3[np.abs(test3) > 3]

Series([], Name: 3, dtype: float64)

In [61]:
test = df1000[0]
test

0     -1.166530
1      0.012628
2      0.149693
3      1.190359
4      1.159677
5      1.094319
6     -1.907632
7     -0.738076
8      1.258306
9      0.966616
10     0.571032
11     0.735289
12     1.169063
13     0.438289
14    -0.580488
15    -0.754160
16     1.276620
17    -0.031363
18     0.163245
19     0.194452
20    -0.213609
21     0.588627
22     1.261048
23    -1.256078
24     1.083548
25     1.973219
26     0.242624
27     1.132613
28    -1.280811
29     0.849051
         ...   
970   -0.023832
971    0.274149
972   -0.035270
973   -0.378096
974   -0.418384
975   -0.360432
976   -1.000022
977   -0.659898
978    0.162693
979   -0.576239
980    0.105342
981    2.840306
982   -2.286187
983   -1.033076
984    0.089179
985    0.675898
986    0.021845
987    0.310561
988   -0.782223
989    0.938490
990    0.746579
991    1.405483
992   -0.578094
993   -0.017188
994   -0.832123
995   -1.530608
996   -0.151214
997   -0.104017
998    1.932427
999    0.193746
Name: 0, Length: 1000, d

In [67]:
test[np.abs(test) > 3]

421   -3.530912
Name: 0, dtype: float64

In [68]:
df1000[(np.abs(df1000) > 3).any(1)]                 #Returns every column containing a value > 3

0         1         2         3
158  0.623798 -0.436479  0.901529 -3.044612
192  0.617561 -1.148738 -3.170292 -1.017073
348  0.813014 -1.202724 -0.286215 -3.105636
360  0.123291 -3.024110 -1.168413 -0.888664
421 -3.530912 -0.576175 -0.750648  0.025443
712 -0.928871  3.061029 -0.297909  0.990886
787  0.836054 -0.780620  0.622791  3.144389

In [69]:
df1000[np.abs(df1000) > 3] = np.sign(df1000)*3    #Any values that are > 3 will turn into - or + 3 depending on original sign

In [70]:
df1000.describe()                                 #Used for capping outliers through logic

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.039328    -0.033386    -0.011579    -0.031852
std       1.002939     0.997895     0.986940     1.012700
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.738643    -0.698731    -0.692887    -0.758010
50%       0.011608    -0.016171     0.022570    -0.035527
75%       0.663800     0.605952     0.666451     0.693491
max       2.916153     3.000000     2.623689     3.000000

In [72]:
#Permutations
df2000 = DataFrame(np.arange(12).reshape(3, 4))

In [78]:
example = np.random.permutation(3)                           #Creates a random permutation of numbers between 0-4

In [79]:
example

array([2, 1, 0])

In [80]:
df2000

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [81]:
df2000.take(example)                                        #Takes random permutation from above and assigns it to indices

0  1   2   3
2  8  9  10  11
1  4  5   6   7
0  0  1   2   3

In [82]:
#Permutation with replacement
box = np.array([2, 4, 6])

In [83]:
box2 = np.random.randint(0, len(box), size = 10)
box2

array([1, 0, 2, 2, 2, 0, 2, 0, 1, 2])

In [85]:
box3 = box.take(box2)
box3

array([4, 2, 6, 6, 6, 2, 6, 2, 4, 6])